//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newspaper.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class abs_miscellaneousEntities : DbContext
    {
        public abs_miscellaneousEntities()
            : base("name=abs_miscellaneousEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<country> country { get; set; }
        public DbSet<category> category { get; set; }
        public DbSet<content> content { get; set; }
        public DbSet<continent> continent { get; set; }
        public DbSet<language> language { get; set; }
    }
}
