//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newspaper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public short categoryid { get; set; }
        public string categoryname { get; set; }
        public bool status { get; set; }
    }
}
