//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newspaper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class continent
    {
        public short continentid { get; set; }
        public string continentname { get; set; }
        public string imagepath { get; set; }
        public bool status { get; set; }
        public string metadescription { get; set; }
        public string metakeywords { get; set; }
    }
}
