//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newspaper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public short id { get; set; }
        public string countrycode { get; set; }
        public string countryname { get; set; }
        public string capital { get; set; }
        public string governmenttype { get; set; }
        public string currencyname { get; set; }
        public string language { get; set; }
        public string location { get; set; }
        public string totalarea { get; set; }
        public Nullable<short> continentid { get; set; }
        public string logo { get; set; }
        public bool status { get; set; }
    }
}
